// DOM Elements
const wordEl = document.querySelector('#word');
const wrongLetterEl = document.querySelector('#wrong-letters');
const playAgainBTN = document.querySelector('.play-again');
const popup = document.querySelector('#popup-container');
const notification = document.querySelector('#notification-container');
const finalMessage = document.querySelector('#final-message');

// Stick Lines
const manParts = document.querySelectorAll('.man-part');

// Word Data
const words = [
    'application',
    'programming',
    'interface',
    'apple',
    'chicken',
    'wizard',
    'hindshank',
    'forehands',
    'wizardries',
    'gimps',
    'tranqs',
    'lice',
    'kegelers',
    'omnirange',
    'dedicator',
    'seedcase',
    'neurasthenias',
    'lippering',
    'notepad',
    'leatherbacks',
    'biofilms',
    'enamor',
    'netting',
    'privileging',
    'hoody',
    'vanillic',
    'ruminate',
    'constatives',
    'linotyped',
    'governorate',
    'pearlashes',
    'parcenaries',
    'hairdressings',
    'journalistic',
    'rugby',
    'mureins',
    'morgue',
    'cracky',
    'marc',
    'physiotherapies',
    'skysurf',
    'bowelled',
    'bisexual',
    'herbiest',
    'quake',
    'cocoplums',
    'wretchedness',
    'strunting',
    'uraei',
    'flauntily',
    'hoorahs',
    'cousinry',
    'ephemeral',
    'chaperoning',
    'ombres',
    'retasted',
    'knaurs',
    'remelting',
    'horsewhip',
    'depigmentations',
    'celeb',
    'despairingly',
    'prefab',
    'retexturing',
    'attestors',
    'questionable',
    'girandolas',
    'pirojki',
    'bounders',
    'depredations',
    'hiccoughs',
    'zygomorphy',
    'autobus',
    'analogizes',
    'gybed',
    'aggressivity',
    'hila',
    'tutor',
    'replication',
    'faradising',
    'caponiers',
    'capitula',
    'incalescences',
    'lolly',
    'deplore',
    'citizenship',
    'temperas',
    'inviolately',
    'puffs',
    'homily',
    'clement',
    'cuttled',
    'saunas',
    'solecize',
    'parashoth',
    'galactorrhea',
    'pomace',
    'cothurnus',
    'announcement',
    'prejudicial',
    'unerring',
    'loathnesses',
    'loreal',
    'provokingly',
    'postelection',
    'usurps',
    'ajugas',
    'etnas',
    'mangosteen',
    'fixated',
    'recode',
    'mythomanias',
    'nonaggressive',
    'marbleized',
    'bedights',
    'aginner',
    'eyestrain',
    'outdueling',
    'earlinesses',
    'compelling',
    'decarbonize',
    'photocopiers',
    'supplements',
    'invaginations',
    'pectizing',
    'crimpled',
    'sparrowlike',
    'eviscerations',
    'witnesses',
    'peckish',
    'nonsecret',
    'parakeets',
    'recaned',
    'gibberishes',
    'mouldered',
    'monotonously',
    'disapprobation',
    'tailboard',
    'republish',
    'handymen',
    'decapitators',
    'irrational',
    'improvidences',
    'endanger',
    'surceases',
    'lurch',
    'bloviating',
    'demander',
    'loudliest',
    'sagest',
    'invasions',
    'coaxes',
    'foxfire',
    'complins',
    'protectory',
    'daydreamers',
    'versines',
    'snakinesses',
    'eastern',
    'ragas',
    'rabbitbrushes',
    'fozy',
    'optometric',
    'famishes',
    'strontiums',
    'scurvies',
    'bronziest',
    'commiserated',
    'exordial',
    'infuriates',
    'mashgihim',
    'russet',
    'senectitude',
    'recognised',
    'upcasts',
    'sunbursts',
    'menstruations',
    'fluffiest',
    'nonloving',
    'radioactively',
    'corium',
    'scrimshaw',
    'pruners',
    'pearlier',
    'soundnesses',
    'golfed',
    'wonders',
    'figuline',
    'outreaching',
    'acquisition',
    'disinflation',
    'act',
    'photooxidizing',
    'ruminantly',
    'picosecond',
    'chloralosed',
    'cockshies',
    'dismasted',
    'dystopian',
    'primos',
    'archaebacterium',
    'chromomeric',
    'flatfeet',
    'feased',
    'inorganically',
    'panners',
    'wallyballs',
    'fomentation',
    'toplessnesses',
    'chlorid',
    'chickweed',
    'envenoms',
    'frigidity',
    'ahorse',
    'pithinesses',
    'anonymous',
    'tremendously',
    'sluttiest',
    'limier',
    'sordors',
    'crowdies',
    'tweenesses',
    'insiders',
    'spatulate',
    'spark',
    'treaters',
    'insolubleness',
    'reasonability',
    'remittable',
    'not',
    'hoodwinks',
    'phoned',
    'bendways',
    'misprinted',
    'puttees',
    'carousals',
    'slipstream',
    'rivieras',
    'mib',
    'radioautographs',
    'erythroblastic',
    'oxygenated',
    'outquoted',
    'unanswerable',
    'aeronautically',
    'nonofficials',
    'lycanthropies',
    'kaleyard',
    'melenas',
    'pastinas',
    'frugivores',
    'overtalk',
    'yawped',
    'misshapes',
    'caginess',
    'morceaux',
    'fluorinating',
    'choreographies',
    'hive',
    'lackeys',
    'cooches',
    'tenebrae',
    'rebalanced',
    'dissert',
    'sensibler',
    'clodpole',
    'gynaecologies',
    'routeway',
    'informedly',
    'el',
    'bethumps',
    'intercountry',
    'hatful',
    'preapproving',
    'unclenching',
    'clearable',
    'fimbria',
    'dislikers',
    'rugosas',
    'mealiness',
    'cloaking',
    'anonymousnesses',
    'moroseness',
    'crossarms',
    'smit',
    'bendable',
    'camphorates',
    'overheaping',
    'unnourishing',
    'valerates',
    'aspires',
    'simnel',
    'grisette',
    'unweaving',
    'cephalexin',
    'glucagon',
    'interiorizing',
    'electroanalysis',
    'tolu',
    'headache',
    'teaboxes',
    'inshrines',
    'kabaka',
    'weavers',
    'defoliated',
    'edifice',
    'patchoulies',
    'aquariums',
    'timber',
    'algebraic',
    'premarital',
    'parties',
    'hemoptysis',
    'entente',
    'perorators',
    'silverpoint',
    'indorsement',
    'plane',
    'precariousness',
    'playless',
    'questions',
    'hajis',
    'rubberier',
    'biconcavities',
    'ploidies',
    'folkmotes',
    'downscaling',
    'observant',
    'copyedits',
    'superagents',
    'trickled',
    'phosphatizes',
    'octuply',
    'exorcised',
    'insanest',
    'unlabored',
    'conservational',
    'ovaries',
    'raveller',
    'armloads',
    'hairiest',
    'artemisias',
    'swooper',
    'samenesses',
    'pretrim',
    'interposer',
    'favour',
    'sloes',
    'caressed',
    'apteria',
    'preemptions',
    'ruggeder',
    'jut',
    'apprehensively',
    'treadles',
    'beclothed',
    'gennakers',
    'factoid',
    'luxate',
    'harpoon',
    'vesiculates',
    'flyblows',
    'berimbau',
    'nicker',
    'press',
    'spins',
    'girlish',
    'bibcocks',
    'fermentor',
    'reorchestrating',
    'redeveloping',
    'paralyzes',
    'lingam',
    'petroleums',
    'fiberfill',
    'enhancing',
    'undoubted',
    'saxtubas',
    'nicotiana',
    'sophist',
    'discommends',
    'calabooses',
    'aggressively',
    'psychs',
    'amandine',
    'raunch',
    'logania',
    'swirled',
    'seisures',
    'gummers',
    'wintery',
    'demoralizers',
    'cosmetically',
    'misparts',
    'scumbags',
    'auxotrophs',
    'perpetuities',
    'microbrewers',
    'tasks',
    'republics',
    'preview',
    'comedo',
    'auditoria',
    'anatto',
    'labyrinth',
    'amnesties',
    'tougheners',
    'saurels',
    'unpriced',
    'gabfests',
    'oxtongues',
    'lispingly',
    'tablatures',
    'victimless',
    'genoms',
    'preadmitting',
    'croupes',
    'nontheatrical',
    'shrive',
    'gauffers',
    'allots',
    'reminiscently',
    'horntails',
    'tincal',
    'button',
    'perspexes',
    'gamekeeper',
    'miraculously',
    'addendum',
    'querulousnesses',
    'precursory',
    'subsecretaries',
    'renaturation',
    'omicron',
    'seminaries',
    'whimsicality',
    'vicariances',
    'equivoque',
    'greenling',
    'manifolded',
    'bendwise',
    'estimating',
    'diuresis',
    'feverfew',
    'cordage',
    'mavericks',
    'pollinizers',
    'cesarian',
    'somnambulists',
    'tokenisms',
    'smushed',
    'womanizing',
    'myelitides',
    'tawdriness',
    'twosome',
    'heterogenies',
    'savvily',
    'deleads',
    'shamefaced',
    'exscinding',
    'randomizes',
    'restocks',
    'punkas',
    'fiscalists',
    'sectored',
    'fulness',
    'telephoner',
    'yarrow',
    'couturieres',
    'legitimatized',
    'ratine',
    'waterer',
    'destitutenesses',
    'housemen',
    'pictogram',
    'heavyset',
    'redry',
    'allspices',
    'hangdogs',
    'estancia',
    'maillot',
    'lordlings',
    'sacrals',
    'polis',
    'superego',
    'sternways',
    'capitularies',
    'fetishizing',
    'polluting',
    'headmen',
    'blighter',
    'hothouse',
    'neurotomies',
    'ozonized',
    'owning',
    'reliabilities',
    'henley',
    'laxative',
    'antipolitical',
    'refunding',
    'sultanesses',
    'outburned',
    'manifestoed',
    'evaginate',
    'unfought',
    'rainmaking',
];
let selectedWord = words[Math.floor(Math.random() * words.length)];
const correctLetters = [];
const wrongLetters = [];

// Show hidden word
function displayWord() {
    wordEl.innerHTML = `
        ${selectedWord
            .split('')
            .map(
                (letter) =>
                    `<span class="letter">
                        ${correctLetters.includes(letter) ? letter : ''}
                    </span>`
            )
            .join('')}
        `;

    const innerWord = wordEl.innerText.replace(/\n/g, '');

    if (innerWord === selectedWord) {
        finalMessage.innerText = 'Congratulations! You won! 😃';
        popup.style.display = 'flex';
    }
}

// Update the wrong letters
function updateWrongLettersEl() {
    //Display Wrong letters
    wrongLetterEl.innerHTML = `
        ${wrongLetters.length > 0 ? '<p>Wrong Letters</p>' : ''}
        ${wrongLetters.map((letter) => `<span> ${letter}</span>`)}
    `;
    //Display Parts
    manParts.forEach((part, index) => {
        const wrongs = wrongLetters.length;
        if (index < wrongs) {
            part.style.display = 'block';
        } else {
            part.style.display = 'none';
        }
    });
    //Check if lost
    if (wrongLetters.length === manParts.length) {
        finalMessage.innerText = `Aw, You lost at guessing ${selectedWord} ` + ':(';
        popup.style.display = 'flex';
    }
}

// Show notification
function showNotification() {
    notification.classList.add('show');
    setTimeout(() => {
        notification.classList.remove('show');
    }, 2000);
}

// Event Listeners
// Keydown letter press
window.addEventListener('keydown', (e) => {
    if (e.keyCode >= 65 && e.keyCode <= 90) {
        const letter = e.key;
        if (selectedWord.includes(letter)) {
            if (!correctLetters.includes(letter)) {
                correctLetters.push(letter);
                displayWord();
            } else {
                showNotification();
            }
        } else {
            if (!wrongLetters.includes(letter)) {
                wrongLetters.push(letter);
                updateWrongLettersEl();
            } else {
                showNotification();
            }
        }
    }
});

//Restart game to play again
playAgainBTN.addEventListener('click', () => {
    correctLetters.splice(0);
    wrongLetters.splice(0);

    selectedWord = words[Math.floor(Math.random() * words.length)];
    displayWord();
    updateWrongLettersEl();
    popup.style.display = 'none';
});

displayWord();
